services:
  - type: web
    name: apsara-api
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        fromGroup: production-settings
      - key: DATABASE_URL
        fromGroup: production-settings
      - key: JWT_SECRET
        fromGroup: production-settings
      - key: YOUTUBE_API_KEY
        fromGroup: production-settings
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
        - requirements.txt
    disk:
      name: uploads
      mountPath: /opt/uploads
      sizeGB: 1